name: snakes
channels:
  - conda-forge
  - defaults
dependencies:
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.2
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - console_shortcut=0.1.1
  - cycler=0.10.0
  - daal4py=2021.2.2
  - dal=2021.2.2
  - decorator=5.0.9
  - et_xmlfile=1.1.0
  - freetype=2.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - intel-openmp=2021.2.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.17.2
  - joblib=1.0.1
  - jpeg=9d
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - kiwisolver=1.3.1
  - lcms2=2.12
  - lerc=2.2.1
  - libdeflate=1.7
  - libiconv=1.15
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.3.0
  - libxml2=2.9.12
  - libxslt=1.1.34
  - lxml=4.6.3
  - lz4-c=1.9.3
  - matplotlib-base=3.4.2
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - numexpr=2.7.3
  - numpy=1.20.2
  - numpy-base=1.20.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openpyxl=3.0.7
  - openssl=1.1.1k
  - pandas=1.2.5
  - parso=0.7.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1.2
  - prompt-toolkit=3.0.17
  - pygments=2.9.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.9.5
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - pywin32=228
  - pyzmq=20.0.0
  - qt=5.9.7
  - scikit-learn=0.24.2
  - scikit-learn-intelex=2021.2.2
  - scipy=1.6.2
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.16.0
  - spyder-kernels=1.10.2
  - sqlite=3.35.4
  - tbb=2021.2.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - tzdata=2021a
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.36.2
  - wincertstore=0.2
  - xz=5.2.5
  - zeromq=4.3.3
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - seaborn==0.11.1
